### ISSUE TITLE
Please rename `Lib` directory to `lib` in the NuGet package

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/Foq#19]
### Description

I had [the following problem](https://travis-ci.org/ForNeVeR/1969/builds/238421750#L1390) when installing Foq on Mono: it has successfully been downloaded by NuGet:

```
Added file 'Foq.dll' to folder '/home/travis/build/ForNeVeR/1969/packages/Foq.1.7.2/Lib/net40'.
Added file 'Foq.XML' to folder '/home/travis/build/ForNeVeR/1969/packages/Foq.1.7.2/Lib/net40'.
Added file 'Foq.dll' to folder '/home/travis/build/ForNeVeR/1969/packages/Foq.1.7.2/Lib/net45'.
Added file 'Foq.XML' to folder '/home/travis/build/ForNeVeR/1969/packages/Foq.1.7.2/Lib/net45'.
Added file 'install.ps1' to folder '/home/travis/build/ForNeVeR/1969/packages/Foq.1.7.2/tools'.
```

But the compiler still complains it can't found `Foq.dll`:

```
			Target ResolveAssemblyReferences:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'Foq' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				Considered ../packages/Foq.1.7.2/lib/net45/Foq.dll, but it does not exist.
```

### Repro steps

1. Create new F# console application.
2. Install Foq from NuGet.
3. Try to build the project on Mono.

### Expected behavior

Project builds without problems.

### Actual behavior

Project fails with the message above.

### Known workarounds

I've solved the problem with [this commit](https://github.com/ForNeVeR/1969/pull/13/commits/54bfc4867ab8d38fac54b4cacf36017cb598c33a), simply changing `lib` to `Lib` in my `fsproj`.

### Related information 

* Operating system: Windows + Visual Studio when installing the package; Linux + Mono when trying to build the program.
* Branch: Foq 1.7.2 from NuGet 
* .NET Runtime, CoreCLR or Mono Version: .NET 4.6.2, Mono 5.0.1.1

**Comment by ptrelford** [comment]
@ForNeVeR thanks for reporting the issue, I'll fix it for the next release

**Comment by saul** [comment]
Foq 1.8.0 has lower-case Lib folders :+1: This can be closed

**Comment by ForNeVeR** [comment]
Confirmed. Thanks!
