### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by saul** [fsprojects/Foq#9]
It'd be really useful if the changes merged in with #8 could be released as a new version on NuGet. At the minute internally we're passing around Foq.fs (from master) and using that instead of the official NuGet source - it's a bit hacky.

Please can a new version be released on NuGet, it'd make our lives so much easier!

Thanks

**Comment by dsyme** [comment]
@ptrelford @sergey-tihon Can you do this?

@saul Perhaps we could give you publishing rights on nuget for this package?

**Comment by sergey-tihon** [comment]
I could try to build the project and create NuGet package
But I do not have access to `fsprojects` account on NuGet, so I cannot publish.

**Comment by saul** [comment]
If @ptrelford isn't around then I'm happy to do it.

**Comment by ptrelford** [comment]
@saul thanks again for your contribution. I was planning to roll up some other changes into the next release but haven't got round to it yet. I'd be more than happy to add you as a package owner on Nuget, so you can push changes out more frequently, just let me know your Nuget username.

**Comment by saul** [comment]
Thanks - my Nuget username is saulren

**Comment by ptrelford** [comment]
No problem, you should get notification from Nuget shortly

**Comment by ptrelford** [comment]
A new version has been pushed to Nuget.
